# Generated by Django 3.2.5 on 2021-07-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('player_id', models.IntegerField(db_index=True)),
                ('games_played', models.IntegerField(db_index=True)),
                ('games_on_roster', models.IntegerField(db_index=True)),
                ('seconds_played', models.FloatField(db_index=True)),
                ('points', models.IntegerField(db_index=True)),
                ('reb_offensive', models.IntegerField(db_index=True)),
                ('reb_defensive', models.IntegerField(db_index=True)),
                ('assists', models.IntegerField(db_index=True)),
                ('steals', models.IntegerField(db_index=True)),
                ('turnovers', models.IntegerField(db_index=True)),
                ('blocks', models.IntegerField(db_index=True)),
                ('ft_made', models.IntegerField(db_index=True)),
                ('ft_missed', models.IntegerField(db_index=True)),
                ('fg_made', models.IntegerField(db_index=True)),
                ('fg_missed', models.IntegerField(db_index=True)),
                ('fg2_made', models.IntegerField(db_index=True)),
                ('fg2_missed', models.IntegerField(db_index=True)),
                ('fg3_made', models.IntegerField(db_index=True)),
                ('fg3_missed', models.IntegerField(db_index=True)),
            ],
            options={
                'db_table': 'player_stats',
            },
        ),
    ]
